# Site settings
title: Casey Leffers Writing Blog
email: leffers.c@husky.neu.edu
description: ""
baseurl: "http://CaseyLeffers.github.io"
url: ""
title_description: ""
title_image: ""
google_analytics: ""
disqus_account: 
github_repository: 
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
author: Casey

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
